draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: auto
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: true
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: ""
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    "&sys_reset": Reset
    "&bootloader": Boot
    "&out OUT_USB": Out USB
    "&out OUT_BLE": Out BLE
    "&bt BT_SEL 0": BT 1
    "&bt BT_SEL 1": BT 2
    "&bt BT_SEL 2": BT 3
    "&bt BT_SEL 3": BT 4
    "&bt BT_SEL 4": BT 5
    SV_A_RING: "Å"
    SV_A_UMLAUT: "Ä"
    SV_O_UMLAUT: "Ö"
    SV_EXCLAMATION: "!"
    SV_EXCL: "!"
    SV_AT_SIGN: "@"
    SV_AT: "@"
    SV_HASH: "#"
    SV_POUND: "#"
    SV_DOLLAR: $
    SV_DLLR: $
    SV_PERCENT: "%"
    SV_PRCNT: "%"
    SV_CARET: ^
    SV_AMPERSAND: "&"
    SV_AMPS: "&"
    SV_ASTERISK: "*"
    SV_ASTRK: "*"
    SV_STAR: "*"
    SV_LEFT_PARENTHESIS: (
    SV_LPAR: (
    SV_RIGHT_PARENTHESIS: )
    SV_RPAR: )
    SV_EQUAL: "="
    SV_PLUS: +
    SV_MINUS: "-"
    SV_UNDERSCORE: _
    SV_UNDER: _
    SV_SLASH: /
    SV_FSLH: /
    SV_QUESTION: "?"
    SV_QMARK: "?"
    SV_BACKSLASH: \
    SV_BSLH: \
    SV_PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SV_SEMICOLON: ;
    SV_SEMI: ;
    SV_COLON: ":"
    SV_SINGLE_QUOTE: "'"
    SV_SQT: "'"
    SV_APOSTROPHE: "'"
    SV_APOS: "'"
    SV_DOUBLE_QUOTES: '"'
    SV_DQT: '"'
    COMMA: ","
    SV_LESS_THAN: <
    SV_LT: <
    PERIOD: .
    DOT: .
    SV_GREATER_THAN: ">"
    SV_GT: ">"
    SV_LEFT_BRACKET: "["
    SV_LBKT: "["
    SV_LEFT_BRACE: "{"
    SV_LBRC: "{"
    SV_RIGHT_BRACKET: "]"
    SV_RBKT: "]"
    SV_RIGHT_BRACE: "}"
    SV_RBRC: "}"
    SV_GRAVE: "`"
    SV_TILDE: "~"
    "&mmv MOVE_UP": 🖱️ ↑
    "&mmv MOVE_DOWN": 🖱️ ↓
    "&mmv MOVE_LEFT": 🖱️ ←
    "&mmv MOVE_RIGHT": 🖱️ →
    "&msc SCRL_UP": 🖱️ ⇈
    "&msc SCRL_DOWN": 🖱️ ⇊
    "&msc SCRL_LEFT": 🖱️ ⇐
    "&msc SCRL_RIGHT": 🖱️ ⇒
    "&mkp LCLK": 🖱️L
    "&mkp RCLK": 🖱️R
    "&mkp MCLK": 🖱️M
  sticky_label: $$mdi:circle-small$$
  toggle_label: $$mdi:toggle-switch$$
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: "{mods}+{key}"
    mod_combiner: "{mod_1}+{mod_2}"
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_remove_keycode_prefix: ["SV_"]
  zmk_keycode_map:
    SPACE: $$mdi:keyboard-space$$
    ESC: $$mdi:keyboard-esc$$
    RETURN: $$mdi:keyboard-return$$
    RET: $$mdi:keyboard-return$$
    BACKSPACE: $$mdi:backspace-outline$$
    BSPC: $$mdi:backspace-outline$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    LGUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    TAB: $$mdi:keyboard-tab$$
    CLCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    A_RING: "Å"
    A_UMLAUT: "Ä"
    O_UMLAUT: "Ö"
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: "="
    PLUS: +
    MINUS: "-"
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: \
    BSLH: \
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ;
    SEMI: ;
    COLON: ":"
    SINGLE_QUOTE: "'"
    SQT: "'"
    APOSTROPHE: "'"
    APOS: "'"
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ","
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"
  zmk_combos: {}
  zmk_preamble: "#define KEYMAP_DRAWER"
  zmk_additional_includes: []
